### ISSUE TITLE
ArrayList instead of HashMap

### ISSUE THREAD

**Issue by VincentFerrigan** [VincentFerrigan/kth-iv1350-object-oriented-design#12]
Explore if it could be more beneficial to use ArrayLists instead of both HashMaps and regular Arrays. What really is the case for keeping HashMaps?

**Comment by VincentFerrigan** [comment]
Or perhaps only switch regular arrays with ArrayLists?

**Comment by VincentFerrigan** [comment]
- [ ] change all x
- [ ] dfsdf
- [ ] sdfsdf
- [ ]

**Comment by blomquiste** [comment]
We are using array list where needed and hash maps in inventory and sale
Puss
